### ISSUE TITLE
ValueError: negative number cannot be raised to a fractional power

### ISSUE THREAD

**Issue by enpassanty** [peliot/XIRR-and-XNPV#3]
I tried using the function to calculate XIRR for the following cashflow:

[(datetime.date(2011, 12, 29), -9000), (datetime.date(2012, 1, 29), 305.38), (datetime.date(2012, 2, 29), 305.38), (datetime.date(2012, 3, 29), 305.38), (datetime.date(2012, 4, 29), 305.38), (datetime.date(2012, 5, 29), 305.38), (datetime.date(2012, 6, 29), 305.38), (datetime.date(2012, 7, 29), 305.38), (datetime.date(2012, 8, 29), 133.04)]

which returns the following error:

return sum([cf/(1+rate)**((t-t0).days/365.0) for (t,cf) in chron_order])
ValueError: negative number cannot be raised to a fractional power

Any idea what's going wrong?

**Comment by peliot** [comment]
Sorry it is not working for you. Here's a quick explanation and some other
thoughts. XIRR is a numerical solver (as you see from the code), which is
solving for the discount rate at which NPV=0. When you have a series of
cash flows with a large negative return (as you do here), NPV as a function
of discount rate looks pretty ugly as function, in such a way that makes it
difficult for numerical solvers to converge on a solution.  I wish the
error messages were more informative, but when you get the error message
you got, it really means that the solver could not converge on a solution
(the reason for that particular error message is that the solver is testing
a value for the discount rate for which NPV has no solution).
Some other thoughts:
- My goal was to be consistent with OpenOffice Calc. If you try the same
  set of cash flows in Calc, you will find that it also throws an error, even
  if you give it the correct answer as a guess. So, this implementation is
  consistent with OO Calc in that regard (though I realize that doesnt help
  you!)
- I realize the explanation above was not super clear, but what it comes
  down to is that XIRR does not perform well for cash flows that represent
  substantial losses (when the answer is near or above -100%). Your example
  is one of these cases.
- Given your cash flows, I would suggest using an IRR function, rather than
  XIRR. There is an IRR function in Numpy. When you have the same period
  between each cash flow, IRR works. XIRR is only necessary when the
  intervals between cash flows are irregular. Since IRR can be solved without
  a numerical solver, it does not suffer from the errors that XIRR yields in
  cases where the answer is a large negative number.

Regards,
Philip

**Comment by enpassanty** [comment]
thanks
